### ISSUE TITLE
wish: generate .desktop files

### ISSUE THREAD

**Issue by markstos** [pvsr/qpm#17]
This issue is for discussing auto-generating `.desktop` files which is listed as a possible future feature in the README.

**Comment by markstos** [comment]
For those looking for this feature, I have a PR to add it to `qutebrowser-profile`:

https://github.com/jtyers/qutebrowser-profile/pull/10

**Comment by markstos** [comment]
Ah, I misread this as not being implemented because the commit linked to simply removes the item from the roadmap. When I looked at a full list of recent commits, I see it's actually implemented: 👍🏼  Thanks!

**Comment by pvsr** [comment]
Whoops, I can see how that was unclear :sweat_smile:
